package OAuthPractise;

public class OAuthPractise1 {
	
	
					//	*********  WHY WE NEED OAuth 2.0 AUTHENTICATION ? **********//
	
	// ALSO CALLED A S THIRD PARTY AUTHENTICATION
	// NO DATA BREACH HEADACHE FOR APPLICATION ( IF IN CASE CLIENT PERSONAL INFORMATION IS LEAKED )
												// THIS CAN CAUSE BILLIONS OF DOLLARS OF FINE
									// BY THIS MECHANISM NOTHING IS SAVED ON YOUR SERVER
									// CENTRALIZED AUTHENTICATION SYSTEM
	// GOOGLE WILL PASS ONLY BASIC INFORMATION TO THE SITE THAT IS TAKING ITS SERVICE ( REMEMBER PASSWORD IS NOT SHARED )
	// LIKE HELLO VIKAS SHARMA -- WELCOME TO UOUR SITE
	// THEY WILL NOT GIVE SECRECT INFORMATION TO THE CLIENT SITE EG. (BOOK MY SHOW)
	// NEED NOT MAINTAIN USER PROFILE DATA
	// COMMON LOGIN FOR HOTEL BOOKING - CAR BOOKING -- RENTAL BOOKING
	// NO NEED TO CREATE DIGFFRENT ACCOUNTS FOR DIFFTRENT WEBSITES
	// NO NEED TO REMEMBER DIFFRENT PASSWORDS AS WELL - ONLY GOOGLE WILL DO ALL 
	// THIS ALLOW RICHER WEBSITES BY ALLOWING DISPERATE APPLICATIONS  TO TALK TO EACH OTHER
	

}
